var namespaceMeadowGames_1_1UINodeConnect4_1_1SampleScene_1_1SerializationSample =
[
    [ "ConnectionColorManager", "classMeadowGames_1_1UINodeConnect4_1_1SampleScene_1_1SerializationSample_1_1ConnectionColorManager.html", "classMeadowGames_1_1UINodeConnect4_1_1SampleScene_1_1SerializationSample_1_1ConnectionColorManager" ],
    [ "CustomPortMatchRule", "classMeadowGames_1_1UINodeConnect4_1_1SampleScene_1_1SerializationSample_1_1CustomPortMatchRule.html", "classMeadowGames_1_1UINodeConnect4_1_1SampleScene_1_1SerializationSample_1_1CustomPortMatchRule" ],
    [ "SerializationManagerSample", "classMeadowGames_1_1UINodeConnect4_1_1SampleScene_1_1SerializationSample_1_1SerializationManagerSample.html", "classMeadowGames_1_1UINodeConnect4_1_1SampleScene_1_1SerializationSample_1_1SerializationManagerSample" ],
    [ "SerializationManagerSampleEditor", "classMeadowGames_1_1UINodeConnect4_1_1SampleScene_1_1SerializationSample_1_1SerializationManagerSampleEditor.html", "classMeadowGames_1_1UINodeConnect4_1_1SampleScene_1_1SerializationSample_1_1SerializationManagerSampleEditor" ]
];